# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 1

project_name: treefmt

before:
    hooks:
        - go mod tidy

builds:
    - env:
          - CGO_ENABLED=0
      ldflags:
          - -s -w -X github.com/numtide/treefmt/build.Version=v{{.Version}}
      goos:
          - linux
          - darwin

# marks the release as draft
# this is to prevent noise until we have a stable 2.x
release:
    draft: true

changelog:
    sort: asc
    use: github
    filters:
        exclude:
            - "^chore:"
            - "^docs:"
            - "^test:"
