queue_rules:
    - name: default
      queue_conditions:
          - base=main
          - label~=merge-queue|dependencies
      merge_conditions:
          - check-success=buildbot/nix-eval
      merge_method: rebase

pull_request_rules:
    - name: refactored queue action rule
      conditions: []
      actions:
          queue:
