# fmt is the universal code formatter - https://github.com/numtide/fmt

[formatters.black]
files = [ "*.py" ]
command = "black"
options = [ ]

[formatters.elm-format]
files = [ "*.elm" ]
command = "elm-format"
options = [ "--yes" ]

[formatters.gofmt]
files = [ "*.go" ]
command = "gofmt"
options = [ "-w" ]

[formatters.ormolu]
files = "*.hs"
excludes = [ "haskell/" ]
command = "ormolu"
options = [
  "--ghc-opt", "-XBangPatterns",
  "--ghc-opt", "-XPatternSynonyms",
  "--ghc-opt", "-XTypeApplications",
  "--mode", "inplace",
  "--check-idempotence"
]

[formatters.prettier]
files = [ "*.js" ]
command = "prettier"
options = [ "--write" ]

[formatters.rustfmt]
files = [ "*.rs" ]
includes = [ "rust/" ]
excludes = []
command = "rustfmt"
options = [ "--edition", "2018" ]

[formatters.shfmt]
files = [ "*.sh" ]
includes = [ "shell/" ]
excludes = []
command = "shfmt"
options = [
  "-i", "2", # indent 2
  "-s", # simplify the code
  "-w", # write back to the file
]
