# fmt is the universal code formatter - https://github.com/numtide/fmt
[ormolu]
includes = [ "haskell/" ]
excludes = []
args = [
  "--ghc-opt", "-XBangPatterns",
  "--ghc-opt", "-XPatternSynonyms",
  "--ghc-opt", "-XTypeApplications",
  "--mode", "inplace",
  "--check-idempotence"
]

[rustfmt]
includes = [ "rust/" ]
excludes = []
args = []
