[manifest.cargo]
command = 'cargo'
args = [
    'fmt',
    '--',
]

[[manifest.cargo.metadata]]
mtimes = 1610965530
path = 'examples/monorepo/rust/src/main.rs'

[manifest.ormolu]
command = 'ormolu'
args = [
    '--ghc-opt',
    '-XBangPatterns',
    '--ghc-opt',
    '-XPatternSynonyms',
    '--ghc-opt',
    '-XTypeApplications',
    '--mode',
    'inplace',
    '--check-idempotence',
]

[[manifest.ormolu.metadata]]
mtimes = 1610928533
path = 'examples/monorepo/haskell/Main.hs'

[[manifest.ormolu.metadata]]
mtimes = 1610352630
path = 'examples/monorepo/haskell/Setup.hs'

[[manifest.ormolu.metadata]]
mtimes = 1610928533
path = 'examples/monorepo/haskell-frontend/Main.hs'

[[manifest.ormolu.metadata]]
mtimes = 1610352630
path = 'examples/monorepo/haskell-frontend/Setup.hs'
